config/routes.rb
Sandy::Application.routes.draw do
  devise_for :users
  resources :posts

  get "about" => "pages#about"

  
  get "nominate" => "pages#nominate"

  root 'pages#welcome'

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
private  
 def mobile?  
   request.user_agent =~ /Mobile|webOS/  
 end 

 helper_method :mobile?

  
  protect_from_forgery with: :exception
  before_action :authenticate_user!, :except => [:show, :about, :post, :welcome, :nominate]
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


  def about
  end

  def welcome
  	@posts = Post.page(params[:page]).order('created_at DESC').per_page(10)
  end

  def scorecard
  end

  def explainer
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]


  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.page(params[:page]).order('created_at DESC').per_page(10)

  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end


  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :image, :kind, :caption, :quote, :content, :audio)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Forgotten Faces of Sandy</title>
    <link rel="icon" 
      href="http://www.google.com/s2/favicons?domain=nj.com">
	  
	 
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    
   
    
<link href='http://fonts.googleapis.com/css?family=News+Cycle:400,700|Oswald' rel='stylesheet' type='text/css'>



    
    
    <% unless mobile? %>
 <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
<%else%>
  <%= stylesheet_link_tag "application" %>
  <meta name="viewport" content="width=320; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;"/>
<% end%>
    
    
     <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>


	</head>
	<body>

     <div class="navbar navbar-default navbar-fixed-top" role="navigation">

  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Forgotten Faces of Sandy", "/", class: "navbar-brand" %>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
  <li class="<%= 'active' if current_page?(about_url) %>"><%= link_to "About", about_url %></li>
  <li class="<%= 'active' if current_page?(nominate_url) %>"><%= link_to "Tell us YOUR story", nominate_url %></li>
          
          </ul>
        </div><!--/.nav-collapse -->
      
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</div>

   <a name="anchor"></a> 
      

  <div id="content">
   
  
    
	<%= yield %>
   
</div>






	</body>
  <div class="col-xs-6">
 
  </div>
<div class="col-xs-6">
<%= link_to "Back to Top", @post, anchor: "anchor", class: "backtotop" %>
 
  </div>
  <script>

 </script>
 <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.2.0/js/bootstrap.min.js"></script>
 
  
	</html>

app/views/pages/about.html.erb
<div class="col-md-8 col-md-offset-2">
<h2>About</h2>
<p>Hurricane Sandy never really left us. The roads might be clear and the National Guardsmen gone, but thousands of New Jerseyans remain displaced nearly two years after the storm.</p>

<p>These are the forgotten faces of Sandy.</p>

<p>NJ.com commissioned photographer Robb Paniconi to document some of those stories in images and sound.</p>

<p>We're still collecting those stories. <a href="http://www.nj.com/news/index.ssf/2014/07/are_you_still_feeling_sandys_impact_we_want_to_hear_from_you.html">Tell us yours here</a>.</p>

We'll be adding more individual stories in the weeks running up to the storm's two-year anniversary on our special project page.

<hr></hr>
<h2>Team</h2>

<p><a href="http://www.RobertPaniconi.com">Robert Paniconi</a> has been photographing in and around the state for years. His focus ranges from social issues to contemporary fine art projects.</p>

<p><a href="http://connect.nj.com/user/CarlaAstudillo/posts.html">Carla Astudillo</a> is a data interactive reporter for NJ.com.</p>

<p><a href="http://connect.nj.com/user/sp_sullivan/posts.html">S.P. Sullivan</a> is a reporter for NJ.com.</p>

<hr></hr>

<p><em>This project was partially funded by a grant from the <a href="http://www.grdodge.org/about-us/new-jersey-recovery-fund/">New Jersey Recovery Fund</a>, through the <a href="http://www.cfnj.org/">Community Foundation of New Jersey</a>.</em></p>



</div>

app/views/pages/nominate.html.erb
<div class="col-md-8 col-md-offset-2">


<h2>Are you a Forgotten Face of Sandy?</h2>
<p>We want to hear your story. Fill out the form below.</p>
<iframe src="https://docs.google.com/forms/d/1HvRe10FpqekvbqVY_YZtRSHV061haTKBva8uA45vjhQ/viewform?embedded=true" width="760" height="900" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
</div>

app/views/pages/welcome.html.erb
<!DOCTYPE html>
<html>
	<head>


  </head>

<% @posts.each do |post| %>

<div class="item">
<%= render 'posts/post', post:post %>
</div>



<% end %>


  <%= will_paginate @posts %>


</body>


 <script>
// init


$(window).load(function(){
	var $container = $('#content');

  $container.isotope({
     itemSelector: '.item',
    layoutMode: 'masonry'
 
});
                 });
	


     $(window).load(function(){
      
$('#content').isotope({
    itemSelector: '.item',
    layoutMode: 'masonry'
  });



$(window).resize(function() {
  var windowwidth= $(window).width();   // returns width of browser viewport
var docwidth = $(document).width();

console.log("This is width:" + docwidth)
if (windowwidth == 841) {
	
}
})


     });

</script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1-rc2/jquery.min.js"></script>
  <script src="http://isotope.metafizzy.co/isotope.pkgd.min.js"></script>
  
	</html>

app/views/posts/_form.html.erb
<div class="col-md-8 col-md-offset-2"><%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
   <%= f.label :kind, "Type of Media?" %><br>
    <%= f.select :kind, ['Image', 'Video'], {}, class: 'form-control' %><br>
  </div>
  
  <div class="form-group">
   <%= f.label :image, "Add link of Image or Video" %><br>
    <%= f.text_area :image, class: 'form-control' %>
  </div>

  <div class="form-group">
   <%= f.label :audio, "Add link to Audio" %><br>
    <%= f.text_area :audio, class: 'form-control' %>
  </div>
  <div class="form-group">
   <%= f.label :caption,  "City" %><br>
    <%= f.text_area :caption, class: 'form-control' %>
  </div>
  <div class="form-group">
   <%= f.label :quote %><br>
    <%= f.text_area :quote, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :content %><br>
    <%= f.text_area :content, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>
</div>

app/views/posts/_moreinfo.html.erb
<iframe width="100%" height="166" scrolling="no" frameborder="no" src="<%= post.audio %>"></iframe>

<%= simple_format post.content %>

</p>
<p class="text-muted"> 
<small>Posted on <%= post.created_at.to_formatted_s(:long_ordinal) %></small>
</p>

<p class="credits">Photos/Audio by Robb Paniconi</p>
<%= render_shareable :turbolinks => true, :buttons=> ['twitter'], :via=> 'njdotcom', :text=> post.title + "'s story" + ' #FacesofSandy' %>

app/views/posts/_post.html.erb
<span class="pull-right"><%= simple_format post.caption %></span>
  <h2><%= link_to post.title, post %></h2>


<p>

<% if !post.image.blank? and post.kind == "Video" %>
	<div class="video-responsive">
 <iframe width="100%" height="100%" frameborder="0" allowfullscreen src="<%= post.image %>"></iframe>
</div>

<p style="margin: 0;font-size: 12px;padding-top: 0.5em;width: 100%;font-weight: bold;text-align: right;display: inline-block;"><%= simple_format post.caption %></p>
  


<% elsif !post.image.blank? and post.kind == "Image" %>
	<%= link_to post do %>
  <%= image_tag post.image, style: "width:100%"%>
<% end %>

 


<% end %>


<% if !post.quote.blank? -%>
<blockquote>
  <%= link_to post.quote, post %>
  
</blockquote>





<% end %>

  

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="col-md-8 col-md-offset-2"><h1>Listing posts</h1>

<table class='table'>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Audio</th>
      <th>Image</th>
      <th>City</th>
      <th>Quote</th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= truncate(post.content, length:70) %></td>
        <td><%= truncate(post.audio, length:10) %></td>
        <td><%= truncate(post.image, length:20) %></td>
        <td><%= truncate(post.caption, length:10) %></td>
        <td><%= truncate(post.quote, length:20) %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

 

<p><%= link_to 'New Post', new_post_path %></p>  <br>  <br>
<p><%= link_to('Logout', destroy_user_session_path, :method => :delete) %> </p>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="col-md-8 col-md-offset-2">
<div class="fullpost">
<%= render 'post', post: @post %> 
<%= render 'moreinfo', post: @post %>
</div>

</div>